blank_issues_enabled: false
contact_links:
  - name: Questions About Contributing
    url: https://github.com/redtaped/ez-startup/discussions/categories/q-a
    about: Please ask and answer questions here.
